version: 0.0
os: linux

files:
  - source: /
    destination: /opt/app/current
    overwrite: true

permissions:
  - object: /opt/app/current
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: codedeploy/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: codedeploy/start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: codedeploy/validate.sh
      timeout: 300
      runas: root
